# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/cv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CVViewerWindow(object):
    def setupUi(self, CVViewerWindow):
        CVViewerWindow.setObjectName("CVViewerWindow")
        CVViewerWindow.resize(900, 700)
        CVViewerWindow.setModal(True)
        CVViewerWindow.setStyleSheet("\n"
"/* Base Dialog Styling - Matches MainWindow and SummaryWindow */\n"
"QDialog {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f8fafc, stop:1 #e2e8f0);\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"/* Header Labels */\n"
"QLabel#lblCVTitle {\n"
"    color: #374151; /* Dark grey */\n"
"    font-weight: bold;\n"
"    font-size: 16px; /* Slightly smaller than main title but prominent */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel#lblFileName {\n"
"    color: #6b7280; /* Greyish text for file info */\n"
"    font-size: 13px;\n"
"    font-style: italic;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Toolbar Frame Styling */\n"
"QFrame#toolbar {\n"
"    background: #ffffff; /* White background for toolbar */\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 12px;\n"
"    margin: 5px; /* Adjust margin to give it space */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* General Button Styling (from MainWindow) */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #6366f1, stop:1 #4f46e5); /* Main button gradient */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    min-width: 80px; /* Ensure a minimum width for all buttons */\n"
"    min-height: 30px; /* Ensure a minimum height for all buttons */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5855eb, stop:1 #4338ca);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #4338ca, stop:1 #3730a3);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #9ca3af;\n"
"    color: #6b7280;\n"
"}\n"
"\n"
"/* Specific Toolbar Button Styling */\n"
"QPushButton#btnZoomIn, QPushButton#btnZoomOut {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #06b6d4, stop:1 #0891b2); /* Cyan gradient */\n"
"    min-width: 60px; /* Smaller width for zoom buttons */\n"
"}\n"
"QPushButton#btnZoomIn:hover, QPushButton#btnZoomOut:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0891b2, stop:1 #0e7490);\n"
"}\n"
"\n"
"QPushButton#btnSaveAs {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f97316, stop:1 #ea580c); /* Orange gradient for Save As */\n"
"}\n"
"QPushButton#btnSaveAs:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ea580c, stop:1 #c2410c);\n"
"}\n"
"\n"
"/* Main Content TextEdit */\n"
"QTextEdit {\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 12px; /* Consistent rounded corners */\n"
"    padding: 15px; /* More padding for content */\n"
"    background: white;\n"
"    font-size: 13px; /* Match general text size */\n"
"    color: #374151; /* Dark grey text */\n"
"}\n"
"\n"
"QTextEdit:read-only {\n"
"    background: #f9fafb; /* Slightly off-white for read-only */\n"
"    color: #6b7280; /* Greyer text for read-only */\n"
"}\n"
"\n"
"/* Bottom Action Buttons */\n"
"QPushButton#btnViewSummary {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #8b5cf6, stop:1 #7c3aed); /* Purple similar to Upload */\n"
"}\n"
"QPushButton#btnViewSummary:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #7c3aed, stop:1 #6d28d9);\n"
"}\n"
"\n"
"QPushButton#btnAnalyzeSkills {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #10b981, stop:1 #059669); /* Green similar to Browse */\n"
"}\n"
"QPushButton#btnAnalyzeSkills:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #059669, stop:1 #047857);\n"
"}\n"
"\n"
"QPushButton#btnPrint {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0ea5e9, stop:1 #0284c7); /* Light blue for Print */\n"
"}\n"
"QPushButton#btnPrint:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0284c7, stop:1 #0369a1);\n"
"}\n"
"\n"
"QPushButton#btnClose {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ef4444, stop:1 #dc2626); /* Red for Close */\n"
"}\n"
"QPushButton#btnClose:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #dc2626, stop:1 #b91c1c);\n"
"}\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(CVViewerWindow)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.lblCVTitle = QtWidgets.QLabel(CVViewerWindow)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblCVTitle.setFont(font)
        self.lblCVTitle.setObjectName("lblCVTitle")
        self.headerLayout.addWidget(self.lblCVTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.lblFileName = QtWidgets.QLabel(CVViewerWindow)
        self.lblFileName.setObjectName("lblFileName")
        self.headerLayout.addWidget(self.lblFileName)
        self.verticalLayout.addLayout(self.headerLayout)
        self.toolbar = QtWidgets.QFrame(CVViewerWindow)
        self.toolbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolbar.setMaximumHeight(50)
        self.toolbar.setObjectName("toolbar")
        self.toolbarLayout = QtWidgets.QHBoxLayout(self.toolbar)
        self.toolbarLayout.setContentsMargins(10, 0, 10, 0)
        self.toolbarLayout.setSpacing(10)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.btnZoomIn = QtWidgets.QPushButton(self.toolbar)
        self.btnZoomIn.setMaximumSize(QtCore.QSize(100, 35))
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.toolbarLayout.addWidget(self.btnZoomIn)
        self.btnZoomOut = QtWidgets.QPushButton(self.toolbar)
        self.btnZoomOut.setMaximumSize(QtCore.QSize(100, 35))
        self.btnZoomOut.setObjectName("btnZoomOut")
        self.toolbarLayout.addWidget(self.btnZoomOut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarLayout.addItem(spacerItem1)
        self.btnSaveAs = QtWidgets.QPushButton(self.toolbar)
        self.btnSaveAs.setMaximumSize(QtCore.QSize(120, 35))
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.toolbarLayout.addWidget(self.btnSaveAs)
        self.verticalLayout.addWidget(self.toolbar)
        self.textCVContent = QtWidgets.QTextEdit(CVViewerWindow)
        self.textCVContent.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.textCVContent.setFont(font)
        self.textCVContent.setObjectName("textCVContent")
        self.verticalLayout.addWidget(self.textCVContent)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setContentsMargins(0, 10, 0, 0)
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnViewSummary = QtWidgets.QPushButton(CVViewerWindow)
        self.btnViewSummary.setMinimumSize(QtCore.QSize(120, 35))
        self.btnViewSummary.setObjectName("btnViewSummary")
        self.buttonLayout.addWidget(self.btnViewSummary)
        self.btnAnalyzeSkills = QtWidgets.QPushButton(CVViewerWindow)
        self.btnAnalyzeSkills.setMinimumSize(QtCore.QSize(120, 35))
        self.btnAnalyzeSkills.setObjectName("btnAnalyzeSkills")
        self.buttonLayout.addWidget(self.btnAnalyzeSkills)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.btnPrint = QtWidgets.QPushButton(CVViewerWindow)
        self.btnPrint.setMinimumSize(QtCore.QSize(80, 35))
        self.btnPrint.setObjectName("btnPrint")
        self.buttonLayout.addWidget(self.btnPrint)
        self.btnClose = QtWidgets.QPushButton(CVViewerWindow)
        self.btnClose.setMinimumSize(QtCore.QSize(80, 35))
        self.btnClose.setObjectName("btnClose")
        self.buttonLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(CVViewerWindow)
        self.btnClose.clicked.connect(CVViewerWindow.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CVViewerWindow)

    def retranslateUi(self, CVViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        CVViewerWindow.setWindowTitle(_translate("CVViewerWindow", "CV Viewer"))
        self.lblCVTitle.setText(_translate("CVViewerWindow", "📄 CV Document Viewer"))
        self.lblFileName.setText(_translate("CVViewerWindow", "File: N/A"))
        self.btnZoomIn.setText(_translate("CVViewerWindow", "➕ Zoom In"))
        self.btnZoomOut.setText(_translate("CVViewerWindow", "➖ Zoom Out"))
        self.btnSaveAs.setText(_translate("CVViewerWindow", "💾 Save As..."))
        self.textCVContent.setPlaceholderText(_translate("CVViewerWindow", "Loading CV content..."))
        self.btnViewSummary.setText(_translate("CVViewerWindow", "📄 View Summary"))
        self.btnAnalyzeSkills.setText(_translate("CVViewerWindow", "💡 Analyze Skills"))
        self.btnPrint.setText(_translate("CVViewerWindow", "🖨️ Print"))
        self.btnClose.setText(_translate("CVViewerWindow", "🚪 Close"))
