# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ui\\icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"/* Main Window Styling */\n"
"QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f8fafc, stop:1 #e2e8f0);\n"
"}\n"
"\n"
"/* Title Label */\n"
"QLabel#lblTitle {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4f46e5, stop:1 #7c3aed);\n"
"    color: white;\n"
"    padding: 15px;\n"
"    border-radius: 12px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"/* Group Box Styling */\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    color: #374151;\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 5px 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4f46e5, stop:1 #7c3aed);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Upload Group Styling */\n"
"QGroupBox#groupUpload {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #fef7ff, stop:1 #f3e8ff);\n"
"    border: 2px solid #c084fc;\n"
"}\n"
"\n"
"/* Search Group Styling */\n"
"QGroupBox#groupSearch {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eff6ff, stop:1 #dbeafe);\n"
"    border: 2px solid #60a5fa;\n"
"}\n"
"\n"
"/* Database Group Styling */\n"
"QGroupBox#groupDatabaseInfo {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0fdf4, stop:1 #dcfce7);\n"
"    border: 2px solid #4ade80;\n"
"}\n"
"\n"
"/* Results Group Styling */\n"
"QGroupBox#groupResults {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #fefce8, stop:1 #fef3c7);\n"
"    border: 2px solid #fbbf24;\n"
"}\n"
"\n"
"/* Button Styling */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #6366f1, stop:1 #4f46e5);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5855eb, stop:1 #4338ca);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #4338ca, stop:1 #3730a3);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #9ca3af;\n"
"    color: #6b7280;\n"
"}\n"
"\n"
"/* Browse Button */\n"
"QPushButton#btnBrowse {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #10b981, stop:1 #059669);\n"
"}\n"
"\n"
"QPushButton#btnBrowse:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #059669, stop:1 #047857);\n"
"}\n"
"\n"
"/* Upload Button */\n"
"QPushButton#btnUpload {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #8b5cf6, stop:1 #7c3aed);\n"
"}\n"
"\n"
"QPushButton#btnUpload:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #7c3aed, stop:1 #6d28d9);\n"
"}\n"
"\n"
"/* Clear Button */\n"
"QPushButton#btnClear {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ef4444, stop:1 #dc2626);\n"
"}\n"
"\n"
"QPushButton#btnClear:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #dc2626, stop:1 #b91c1c);\n"
"}\n"
"\n"
"/* Input Fields */\n"
"QLineEdit {\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    background: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #6366f1;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:read-only {\n"
"    background: #f9fafb;\n"
"    color: #6b7280;\n"
"}\n"
"\n"
"/* Spin Box */\n"
"QSpinBox {\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background: white;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border-color: #6366f1;\n"
"}\n"
"\n"
"/* Radio Buttons */\n"
"QRadioButton {\n"
"    font-size: 13px;\n"
"    color: #374151;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #d1d5db;\n"
"    border-radius: 9px;\n"
"    background: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid #6366f1;\n"
"    border-radius: 9px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6366f1, stop:1 #4f46e5);\n"
"}\n"
"\n"
"/* List Widgets */\n"
"QListWidget {\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"    alternate-background-color: #f9fafb;\n"
"    selection-background-color: #6366f1;\n"
"    selection-color: white;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #f3f4f6;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #f3f4f6;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #6366f1, stop:1 #4f46e5);\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #374151;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLabel#lblPerformanceTitle {\n"
"    color: #059669;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Menu Bar */\n"
"QMenuBar {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #1f2937, stop:1 #111827);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #374151;\n"
"}\n"
"\n"
"QMenu {\n"
"    background: white;\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 8px 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: #f3f4f6;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background: #f9fafb;\n"
"    border-top: 1px solid #e5e7eb;\n"
"    color: #6b7280;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(20, 10, 1360, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.groupUpload = QtWidgets.QGroupBox(self.centralwidget)
        self.groupUpload.setGeometry(QtCore.QRect(20, 90, 670, 120))
        self.groupUpload.setObjectName("groupUpload")
        self.lineEditFilePath = QtWidgets.QLineEdit(self.groupUpload)
        self.lineEditFilePath.setGeometry(QtCore.QRect(20, 40, 420, 35))
        self.lineEditFilePath.setReadOnly(True)
        self.lineEditFilePath.setClearButtonEnabled(False)
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.btnBrowse = QtWidgets.QPushButton(self.groupUpload)
        self.btnBrowse.setGeometry(QtCore.QRect(450, 60, 100, 35))
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnUpload = QtWidgets.QPushButton(self.groupUpload)
        self.btnUpload.setEnabled(True)
        self.btnUpload.setGeometry(QtCore.QRect(560, 60, 100, 35))
        self.btnUpload.setMouseTracking(True)
        self.btnUpload.setObjectName("btnUpload")
        self.inputIDApplicants = QtWidgets.QLineEdit(self.groupUpload)
        self.inputIDApplicants.setGeometry(QtCore.QRect(20, 80, 421, 31))
        self.inputIDApplicants.setReadOnly(False)
        self.inputIDApplicants.setClearButtonEnabled(True)
        self.inputIDApplicants.setObjectName("inputIDApplicants")
        self.groupSearch = QtWidgets.QGroupBox(self.centralwidget)
        self.groupSearch.setGeometry(QtCore.QRect(20, 230, 670, 200))
        self.groupSearch.setObjectName("groupSearch")
        self.lblKeywords = QtWidgets.QLabel(self.groupSearch)
        self.lblKeywords.setGeometry(QtCore.QRect(20, 35, 100, 25))
        self.lblKeywords.setObjectName("lblKeywords")
        self.inputKeywords = QtWidgets.QLineEdit(self.groupSearch)
        self.inputKeywords.setGeometry(QtCore.QRect(130, 35, 400, 35))
        self.inputKeywords.setObjectName("inputKeywords")
        self.btnSearch = QtWidgets.QPushButton(self.groupSearch)
        self.btnSearch.setGeometry(QtCore.QRect(540, 35, 120, 35))
        self.btnSearch.setObjectName("btnSearch")
        self.lblAlgorithm = QtWidgets.QLabel(self.groupSearch)
        self.lblAlgorithm.setGeometry(QtCore.QRect(20, 85, 100, 25))
        self.lblAlgorithm.setObjectName("lblAlgorithm")
        self.radioKMP = QtWidgets.QRadioButton(self.groupSearch)
        self.radioKMP.setGeometry(QtCore.QRect(130, 85, 95, 25))
        self.radioKMP.setObjectName("radioKMP")
        self.radioBoyerMoore = QtWidgets.QRadioButton(self.groupSearch)
        self.radioBoyerMoore.setGeometry(QtCore.QRect(240, 85, 130, 25))
        self.radioBoyerMoore.setObjectName("radioBoyerMoore")
        self.radioAhoCorasick = QtWidgets.QRadioButton(self.groupSearch)
        self.radioAhoCorasick.setGeometry(QtCore.QRect(385, 85, 130, 25))
        self.radioAhoCorasick.setChecked(True)
        self.radioAhoCorasick.setObjectName("radioAhoCorasick")
        self.lblResultLimit = QtWidgets.QLabel(self.groupSearch)
        self.lblResultLimit.setGeometry(QtCore.QRect(20, 125, 100, 25))
        self.lblResultLimit.setObjectName("lblResultLimit")
        self.spinResultLimit = QtWidgets.QSpinBox(self.groupSearch)
        self.spinResultLimit.setGeometry(QtCore.QRect(130, 125, 80, 30))
        self.spinResultLimit.setMinimum(1)
        self.spinResultLimit.setMaximum(100)
        self.spinResultLimit.setProperty("value", 10)
        self.spinResultLimit.setObjectName("spinResultLimit")
        self.btnClear = QtWidgets.QPushButton(self.groupSearch)
        self.btnClear.setGeometry(QtCore.QRect(540, 125, 120, 35))
        self.btnClear.setObjectName("btnClear")
        self.groupDatabaseInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupDatabaseInfo.setGeometry(QtCore.QRect(710, 90, 670, 340))
        self.groupDatabaseInfo.setObjectName("groupDatabaseInfo")
        self.lblTotalCVs = QtWidgets.QLabel(self.groupDatabaseInfo)
        self.lblTotalCVs.setGeometry(QtCore.QRect(20, 35, 300, 25))
        self.lblTotalCVs.setStyleSheet("font-weight: bold; color: #059669;")
        self.lblTotalCVs.setObjectName("lblTotalCVs")
        self.lblLastUpload = QtWidgets.QLabel(self.groupDatabaseInfo)
        self.lblLastUpload.setGeometry(QtCore.QRect(20, 65, 400, 25))
        self.lblLastUpload.setObjectName("lblLastUpload")
        self.lblRecentCVs = QtWidgets.QLabel(self.groupDatabaseInfo)
        self.lblRecentCVs.setGeometry(QtCore.QRect(20, 105, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lblRecentCVs.setFont(font)
        self.lblRecentCVs.setObjectName("lblRecentCVs")
        self.listRecentCVs = QtWidgets.QListWidget(self.groupDatabaseInfo)
        self.listRecentCVs.setGeometry(QtCore.QRect(20, 135, 630, 180))
        self.listRecentCVs.setObjectName("listRecentCVs")
        self.groupResults = QtWidgets.QGroupBox(self.centralwidget)
        self.groupResults.setGeometry(QtCore.QRect(20, 450, 1360, 380))
        self.groupResults.setObjectName("groupResults")
        self.listResults = QtWidgets.QListWidget(self.groupResults)
        self.listResults.setGeometry(QtCore.QRect(20, 35, 900, 320))
        self.listResults.setObjectName("listResults")
        self.btnViewSummary = QtWidgets.QPushButton(self.groupResults)
        self.btnViewSummary.setEnabled(False)
        self.btnViewSummary.setGeometry(QtCore.QRect(940, 50, 140, 40))
        self.btnViewSummary.setObjectName("btnViewSummary")
        self.btnViewCV = QtWidgets.QPushButton(self.groupResults)
        self.btnViewCV.setEnabled(False)
        self.btnViewCV.setGeometry(QtCore.QRect(940, 100, 140, 40))
        self.btnViewCV.setObjectName("btnViewCV")
        self.lblPerformanceTitle = QtWidgets.QLabel(self.groupResults)
        self.lblPerformanceTitle.setGeometry(QtCore.QRect(1100, 50, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblPerformanceTitle.setFont(font)
        self.lblPerformanceTitle.setObjectName("lblPerformanceTitle")
        self.lblExactMatchTime = QtWidgets.QLabel(self.groupResults)
        self.lblExactMatchTime.setGeometry(QtCore.QRect(1100, 80, 240, 25))
        self.lblExactMatchTime.setObjectName("lblExactMatchTime")
        self.lblFuzzyMatchTime = QtWidgets.QLabel(self.groupResults)
        self.lblFuzzyMatchTime.setGeometry(QtCore.QRect(1100, 110, 240, 25))
        self.lblFuzzyMatchTime.setObjectName("lblFuzzyMatchTime")
        self.lblTotalResults = QtWidgets.QLabel(self.groupResults)
        self.lblTotalResults.setGeometry(QtCore.QRect(1100, 140, 240, 25))
        self.lblTotalResults.setObjectName("lblTotalResults")
        self.progressBar = QtWidgets.QProgressBar(self.groupResults)
        self.progressBar.setGeometry(QtCore.QRect(1100, 180, 240, 25))
        self.progressBar.setStyleSheet("\n"
"QProgressBar {\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 12px;\n"
"    background: #f9fafb;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #10b981, stop:1 #059669);\n"
"    border-radius: 10px;\n"
"}\n"
"      ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 45))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.lblStatus = QtWidgets.QLabel(self.statusbar)
        self.lblStatus.setGeometry(QtCore.QRect(10, 5, 200, 20))
        self.lblStatus.setObjectName("lblStatus")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUploadCV = QtWidgets.QAction(MainWindow)
        self.actionUploadCV.setObjectName("actionUploadCV")
        self.actionExportResults = QtWidgets.QAction(MainWindow)
        self.actionExportResults.setObjectName("actionExportResults")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNewSearch = QtWidgets.QAction(MainWindow)
        self.actionNewSearch.setObjectName("actionNewSearch")
        self.actionClearResults = QtWidgets.QAction(MainWindow)
        self.actionClearResults.setObjectName("actionClearResults")
        self.actionSearchSettings = QtWidgets.QAction(MainWindow)
        self.actionSearchSettings.setObjectName("actionSearchSettings")
        self.actionRefreshDatabase = QtWidgets.QAction(MainWindow)
        self.actionRefreshDatabase.setObjectName("actionRefreshDatabase")
        self.actionDatabaseStats = QtWidgets.QAction(MainWindow)
        self.actionDatabaseStats.setObjectName("actionDatabaseStats")
        self.actionClearDatabase = QtWidgets.QAction(MainWindow)
        self.actionClearDatabase.setObjectName("actionClearDatabase")
        self.actionUserGuide = QtWidgets.QAction(MainWindow)
        self.actionUserGuide.setObjectName("actionUserGuide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionUploadCV)
        self.menuFile.addAction(self.actionExit)
        self.menuDatabase.addAction(self.actionRefreshDatabase)
        self.menuDatabase.addAction(self.actionClearDatabase)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CV Search System - Professional Edition"))
        self.lblTitle.setText(_translate("MainWindow", "🔍 Masih HR Magang ? Anda datang ke tempat yang tepat"))
        self.groupUpload.setTitle(_translate("MainWindow", "📤 Upload CV"))
        self.lineEditFilePath.setPlaceholderText(_translate("MainWindow", "📄 Select PDF file to upload..."))
        self.btnBrowse.setText(_translate("MainWindow", "📂 Browse"))
        self.btnUpload.setText(_translate("MainWindow", "⬆️ Upload"))
        self.inputIDApplicants.setPlaceholderText(_translate("MainWindow", "Enter ID Applicants"))
        self.groupSearch.setTitle(_translate("MainWindow", "🔍 Search Configuration"))
        self.lblKeywords.setText(_translate("MainWindow", "🏷️ Keywords:"))
        self.inputKeywords.setPlaceholderText(_translate("MainWindow", "Enter search keywords (separated by comma)"))
        self.btnSearch.setText(_translate("MainWindow", "🔍 Search"))
        self.lblAlgorithm.setText(_translate("MainWindow", "⚙️ Algorithm:"))
        self.radioKMP.setText(_translate("MainWindow", "KMP"))
        self.radioBoyerMoore.setText(_translate("MainWindow", "Boyer-Moore"))
        self.radioAhoCorasick.setText(_translate("MainWindow", "Aho-Corasick"))
        self.lblResultLimit.setText(_translate("MainWindow", "📊 Results:"))
        self.btnClear.setText(_translate("MainWindow", "🗑️ Clear"))
        self.groupDatabaseInfo.setTitle(_translate("MainWindow", "💾 Database Information"))
        self.lblTotalCVs.setText(_translate("MainWindow", "📁 Total CVs in Database: 0"))
        self.lblLastUpload.setText(_translate("MainWindow", "⏰ Last Upload: Never"))
        self.lblRecentCVs.setText(_translate("MainWindow", "📋 Recent CVs:"))
        self.groupResults.setTitle(_translate("MainWindow", "📈 Search Results"))
        self.btnViewSummary.setText(_translate("MainWindow", "📄 View Summary"))
        self.btnViewCV.setText(_translate("MainWindow", "👁️ View Full CV"))
        self.lblPerformanceTitle.setText(_translate("MainWindow", "⚡ Performance Metrics:"))
        self.lblExactMatchTime.setText(_translate("MainWindow", "🎯 Exact Match: - ms"))
        self.lblFuzzyMatchTime.setText(_translate("MainWindow", "🔍 Fuzzy Match: - ms"))
        self.lblTotalResults.setText(_translate("MainWindow", "📊 Total Results: 0"))
        self.menuFile.setTitle(_translate("MainWindow", "📁 File"))
        self.menuDatabase.setTitle(_translate("MainWindow", "💾 Database"))
        self.lblStatus.setText(_translate("MainWindow", "✅ Ready - System Initialized"))
        self.actionUploadCV.setText(_translate("MainWindow", "📤 Upload CV"))
        self.actionUploadCV.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExportResults.setText(_translate("MainWindow", "💾 Export Results"))
        self.actionExportResults.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "🚪 Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNewSearch.setText(_translate("MainWindow", "🆕 New Search"))
        self.actionNewSearch.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionClearResults.setText(_translate("MainWindow", "🗑️ Clear Results"))
        self.actionClearResults.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSearchSettings.setText(_translate("MainWindow", "⚙️ Search Settings"))
        self.actionRefreshDatabase.setText(_translate("MainWindow", "🔄 Refresh Database"))
        self.actionRefreshDatabase.setShortcut(_translate("MainWindow", "F5"))
        self.actionDatabaseStats.setText(_translate("MainWindow", "📈 Database Statistics"))
        self.actionClearDatabase.setText(_translate("MainWindow", "🗑️ Clear Database"))
        self.actionUserGuide.setText(_translate("MainWindow", "📖 User Guide"))
        self.actionUserGuide.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "ℹ️ About"))
